print "Starting maya loading and fbx conversion \n";
	
if (`file -q -exists "/Users/corbinwalker/Documents/Digital Media/Digital-Media/2018 Game/Assets/Resources/MayaModels/cratermesh.ma"`)
{		
	file -o "/Users/corbinwalker/Documents/Digital Media/Digital-Media/2018 Game/Assets/Resources/MayaModels/cratermesh.ma";
	FBXExportEmbeddedTextures -v false;
	// FBXExportHardEdges -v true;
	FBXExportApplyConstantKeyReducer -v false;
	FBXExportShowUI -v false;

	print "Before fbx export\n";
	FBXExport -f "/Users/corbinwalker/Documents/Digital Media/Digital-Media/2018 Game/Temp/ExportedFBXFile.fbx";
	print "after fbx export\n";
}
else
	print "Could not open Maya file.";

sysFile -delete "/Users/corbinwalker/Documents/Digital Media/Digital-Media/2018 Game/Temp/CommandPipe";

$donepipeKill = `fopen "/Users/corbinwalker/Documents/Digital Media/Digital-Media/2018 Game/Temp/SyncPipeKill" "w"`;
fwrite $donepipeKill "Done";
fclose $donepipeKill;
